require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.nvim-tree"
require "user.lualine"
require "user.autopairs"
require "user.gitsigns"
require "user.sessions"
require "user.toggleterm"
require "user.nvim-test"
require "user.colorizer"
require "user.delete_hidden_buffers"

