require "user.options"
require "user.impatient"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.nvim-tree"
require "user.lualine"
require "user.autopairs"
require "user.gitsigns"
require "user.sessions"
require "user.toggleterm"
-- require "user.neoterm"
require "user.nvim-test"
require "user.colorizer"
require "user.grepper"
require "user.trouble"
require "user.project"
require "user.alpha"
require "user.which-key"
require "user.harpoon"

-- Disabled until I muster the energy to make them work --
-- require "user.projectionist"
-- require "user.delete_hidden_buffers"
